-- XX: Generated by a LLM.
module YQL.PrettyPrint (displayYQL) where

import Data.List (intersperse)
import YQL.AST (Node (..))

class Print a where
  prt :: Int -> a -> ShowS

displayYQL :: Node -> String
displayYQL x = prt 0 x "\n"

indent :: Int -> ShowS
indent n = showString (replicate (2 * n) ' ')

nl :: Int -> ShowS
nl i = showChar '\n' . indent i

sepSpc :: [ShowS] -> ShowS
sepSpc ss = foldr (.) id (intersperse (showChar ' ') ss)

prettyBlockQuotedCompact :: Int -> [Node] -> ShowS
prettyBlockQuotedCompact headerIndent stmts =
  showChar '('
    . showString "block '("
    . foldr
      (\st r -> nl (headerIndent + 1) . prt (headerIndent + 1) st . r)
      id
      stmts
    . nl headerIndent
    . showString "))"

prettyBlock :: Int -> [Node] -> ShowS
prettyBlock i [Q (Y stmts)] =
  prettyBlockQuotedCompact i stmts
prettyBlock i args =
  showChar '('
    . showString "block"
    . foldr (\a r -> nl (i + 1) . prt (i + 1) a . r) id args
    . nl i
    . showChar ')'

isStmt :: Node -> Bool
isStmt (Y (A "let" : _)) = True
isStmt (Y (A "declare" : _)) = True
isStmt (Y (A "return" : _)) = True
isStmt (Y (A "block" : _)) = True
isStmt _ = False

isStmtList :: [Node] -> Bool
isStmtList xs = length xs > 1 && all isStmt xs

prtInline :: Node -> ShowS
prtInline (A s) = showString s
prtInline (Q x) = prt 0 (Q x)
prtInline (Y []) = showString "()"
prtInline (Y xs) = showChar '(' . sepSpc (map prtInline xs) . showChar ')'

prtApply :: [Node] -> ShowS
prtApply xs = showChar '(' . sepSpc (map prtInline xs) . showChar ')'

instance Print Node where
  prt _ (A s) = showString s
  prt _ (Q (A s)) = showChar '\'' . showString s
  prt _ (Q (Y [])) = showChar '\'' . showString "()"
  prt _ (Q (Y [x])) = showChar '\'' . showChar '(' . prtInline x . showChar ')'
  prt i (Q (Y xs))
    | isStmtList xs =
        showChar '\''
          . showChar '('
          . foldr (\x r -> nl (i + 1) . prt (i + 1) x . r) id xs
          . nl i
          . showChar ')'
  prt _ (Q (Y xs)) =
    showChar '\'' . showChar '(' . sepSpc (map prtInline xs) . showChar ')'
  prt i (Q (Q x)) = showChar '\'' . prt i (Q x)
  prt _ (Y []) = showString "()"
  prt i (Y [x]) = showChar '(' . prt i x . showChar ')'
  prt i (Y [A "let", name, Y [A "lambda", qps, body]]) =
    showChar '('
      . showString "let "
      . prtInline name
      . showChar ' '
      . prt i (Y [A "lambda", qps, body])
      . showChar ')'
  prt i (Y [A "lambda", qps, Y [A "block", Q (Y stmts)]]) =
    showChar '('
      . showString "lambda "
      . prtInline qps
      . showChar ' '
      . prettyBlockQuotedCompact i stmts
      . showChar ')'
  prt i (Y [A "lambda", qps, body]) =
    showChar '('
      . showString "lambda "
      . prtInline qps
      . nl (i + 1)
      . prt (i + 1) body
      . showChar ')'
  prt i (Y (A "block" : args)) =
    prettyBlock i args
  prt i (Y [A "let", name, expr]) =
    showChar '('
      . showString "let "
      . prtInline name
      . showChar ' '
      . prt (i + 1) expr
      . showChar ')'
  prt _ (Y xs@(A "declare" : _)) = prtApply xs
  prt _ (Y xs@(A "return" : _)) = prtApply xs
  prt i (Y xs)
    | isStmtList xs =
        showChar '('
          . foldr (\x r -> nl (i + 1) . prt (i + 1) x . r) id xs
          . nl i
          . showChar ')'
  prt _ (Y xs) = prtApply xs
