-- XX: Generated by a LLM.
module YQL.PrettyPrint (displayYQL) where

import Data.List (intersperse)
import YQL.AST (Node (..))

class Print a where
  prt :: Int -> a -> ShowS

displayYQL :: Node -> String
displayYQL x = prt 0 x ""

-- | Target width for keeping parenthesized applications on one line.
maxLineWidth :: Int
maxLineWidth = 100

indent :: Int -> ShowS
indent n = showString (replicate (2 * n) ' ')

nl :: Int -> ShowS
nl i = showChar '\n' . indent i

sepSpc :: [ShowS] -> ShowS
sepSpc ss = foldr (.) id (intersperse (showChar ' ') ss)

prettyBlockQuotedCompact :: Int -> [Node] -> ShowS
prettyBlockQuotedCompact headerIndent stmts =
  showChar '('
    . showString "block '("
    . foldr
      (\st r -> nl (headerIndent + 1) . prt (headerIndent + 1) st . r)
      id
      stmts
    . showString "))"

prettyBlock :: Int -> [Node] -> ShowS
prettyBlock i [Q (Y stmts)] =
  prettyBlockQuotedCompact i stmts
prettyBlock i args =
  showChar '('
    . showString "block"
    . foldr (\a r -> nl (i + 1) . prt (i + 1) a . r) id args
    . nl i
    . showChar ')'

isStmt :: Node -> Bool
isStmt (Y (A "let" : _)) = True
isStmt (Y (A "declare" : _)) = True
isStmt (Y (A "return" : _)) = True
isStmt (Y (A "block" : _)) = True
isStmt _ = False

isStmtList :: [Node] -> Bool
isStmtList xs = length xs > 1 && all isStmt xs

-- | Approximate width if the node were printed flat on one line.
flatWidth :: Node -> Int
flatWidth (A s) = length s
flatWidth (Q x) = 1 + flatWidth x
flatWidth (Y []) = 2
flatWidth (Y xs) =
  2 + sum (map flatWidth xs) + max 0 (length xs - 1)

-- | Layout that always uses newlines (blocks and statement lists).
hasForcedLayout :: Node -> Bool
hasForcedLayout (Y xs) | isStmtList xs = True
hasForcedLayout (Y (A "block" : _)) = True
hasForcedLayout (Y [A "lambda", _, Y [A "block", _]]) = True
hasForcedLayout (Y [A "lambda", _, body]) = hasForcedLayout body
hasForcedLayout (Y [A "let", _, expr]) = hasForcedLayout expr
hasForcedLayout (Y [x]) = hasForcedLayout x
hasForcedLayout (Y xs) = any hasForcedLayout xs
hasForcedLayout (Q (Y xs)) | isStmtList xs = True
hasForcedLayout (Q x) = hasForcedLayout x
hasForcedLayout _ = False

-- | True if the node can be printed on a single line within 'maxLineWidth'.
fitsSingleLine :: Node -> Bool
fitsSingleLine n
  | hasForcedLayout n = False
  | flatWidth n > maxLineWidth = False
fitsSingleLine (A _) = True
fitsSingleLine (Q x) = fitsSingleLine x
fitsSingleLine (Y [x]) = fitsSingleLine x
fitsSingleLine (Y xs) = all fitsSingleLine xs

prtApply :: Int -> [Node] -> ShowS
prtApply i xs =
  let n = Y xs
  in if fitsSingleLine n
      then showChar '(' . sepSpc (map (prt i) xs) . showChar ')'
      else case xs of
        y : ys ->
          showChar '('
            . prt (i + 1) y
            . foldr (\x r -> nl (i + 1) . prt (i + 1) x . r) id ys
            . showChar ')'
        [] -> showString "()"

instance Print Node where
  prt _ (A s) = showString s
  prt _ (Q (A s)) = showChar '\'' . showString s
  prt _ (Q (Y [])) = showChar '\'' . showString "()"
  prt i (Q (Y [x])) = showChar '\'' . showChar '(' . prt i x . showChar ')'
  prt i (Q (Y xs))
    | isStmtList xs =
        showChar '\''
          . showChar '('
          . foldr (\x r -> nl (i + 1) . prt (i + 1) x . r) id xs
          . nl i
          . showChar ')'
  prt i (Q (Y xs)) =
    showChar '\'' . showChar '(' . sepSpc (map (prt i) xs) . showChar ')'
  prt i (Q (Q x)) = showChar '\'' . prt i (Q x)
  prt _ (Y []) = showString "()"
  prt i (Y [x]) = showChar '(' . prt i x . showChar ')'
  prt i (Y [A "let", name, lam@(Y [A "lambda", _, Y [A "block", _]])]) =
    showChar '('
      . showString "let "
      . prt i name
      . showChar ' '
      . prt i lam
      . showChar ')'
  prt i letLam@(Y [A "let", name, Y [A "lambda", qps, body]])
    | fitsSingleLine letLam =
        showChar '('
          . showString "let "
          . prt i name
          . showChar ' '
          . prt i (Y [A "lambda", qps, body])
          . showChar ')'
    | otherwise =
        showChar '('
          . showString "let "
          . prt i name
          . showChar ' '
          . showChar '('
          . showString "lambda "
          . prt i qps
          . nl (i + 1)
          . prt (i + 1) body
          . showChar ')'
          . showChar ')'
  prt i (Y [A "lambda", qps, Y [A "block", Q (Y stmts)]]) =
    showChar '('
      . showString "lambda "
      . prt i qps
      . showChar ' '
      . prettyBlockQuotedCompact i stmts
      . showChar ')'
  prt i lam@(Y [A "lambda", qps, body])
    | fitsSingleLine lam =
        showChar '('
          . showString "lambda "
          . prt i qps
          . showChar ' '
          . prt i body
          . showChar ')'
    | otherwise =
        showChar '('
          . showString "lambda "
          . prt i qps
          . nl (i + 1)
          . prt (i + 1) body
          . showChar ')'
  prt i (Y (A "block" : args)) =
    prettyBlock i args
  prt i letNode@(Y [A "let", name, expr])
    | fitsSingleLine letNode =
        showChar '('
          . showString "let "
          . prt i name
          . showChar ' '
          . prt i expr
          . showChar ')'
    | otherwise =
        showChar '('
          . showString "let "
          . prt i name
          . nl (i + 1)
          . prt (i + 1) expr
          . showChar ')'
  prt i (Y xs@(A "declare" : _)) = prtApply i xs
  prt i (Y [A "return", body@(Y (A "block" : _))]) =
    showChar '('
      . showString "return "
      . prt i body
      . showChar ')'
  prt i (Y xs@(A "return" : _)) = prtApply i xs
  prt i (Y xs)
    | isStmtList xs =
        showChar '('
          . foldr (\x r -> nl (i + 1) . prt (i + 1) x . r) id xs
          . nl i
          . showChar ')'
  prt i (Y xs) = prtApply i xs
