name: Haskell

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'vscode/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'vscode/**'
  workflow_call:

jobs:
  haskell:
    name: Haskell
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: '3.3.1'

      - name: Cache Stack Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'package.yaml') }}
          restore-keys: ${{ runner.os }}-stack-

      - name: Install HPack
        run: make install-hpack

      - name: Install BNFC
        run: make install-bnfc

      - name: Generate SyntaxGen Module
        run: make generate-syntaxgen-module

      - name: Generate Yson.SyntaxGen Module
        run: make generate-yson-syntaxgen-module

      - name: Generate Cabal File
        run: make generate-cabal-file

      - name: Build Dependencies
        run: make build-dependencies

      - name: Build Project
        run: make build-project

      - name: Test
        run: make test

      - name: Install Ormolu
        run: make install-ormolu

      - name: Check Haskell Formatting
        run: make check-haskell-formatting

      - name: Install HLint
        run: make install-hlint

      - name: Check Haskell Style
        run: make check-haskell-style

      - name: Copy Binary
        run: cp "$(stack path --local-install-root)/bin/yqstella" "$RUNNER_TEMP/yqstella"

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: yqstella
          path: ${{ runner.temp }}/yqstella
          retention-days: 1
