name: Other

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.bash'
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '**.bash'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          sudo apt-get install -y shellcheck

      - name: Check Shell Style
        run: |
          find . -name "*.bash" -type f | while read f; do
            shellcheck "$f" || exit 1
          done

      - name: Install MarkdownLint
        run: |
          npm install -g markdownlint-cli

      - name: Check Markdown Style
        run: |
          find . -name "*.md" -type f | while read f; do
            markdownlint "$f" || exit 1
          done
